// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://osgsnmmwecytiplphsth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zZ3NubW13ZWN5dGlwbHBoc3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTk5NzIsImV4cCI6MjA3MDIzNTk3Mn0.xX3Hjg4do-pXK8i9c8LLm5nSTTDNQYPiZu-n40iYYS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);